In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [ ]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:

from sklearn.preprocessing import LabelEncoder

x = df.drop("Purchased", axis=1)
le = LabelEncoder()
x['Gender'] = le.fit_transform(x['Gender'])
y = df["Purchased"]

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest =train_test_split(x, y, test_size =0.2,random_state = 0)
import sklearn
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(xtrain,ytrain)

LogisticRegression()

In [ ]:
ytrain_pred = model.predict(xtrain)
ytest_pred =model.predict(xtest)

In [ ]:
df=pd.DataFrame(ytrain_pred,ytrain)
df=pd.DataFrame(ytest_pred,ytest)

In [ ]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score

Confusion Matrix

In [ ]:
cm=confusion_matrix(ytest,ytest_pred)
cm

array([[56,  2],
       [ 5, 17]])

Precision Score

In [ ]:
ps=precision_score(ytest,ytest_pred)
ps

0.8947368421052632

Accuracy Score

In [ ]:
acc_score=accuracy_score(ytest,ytest_pred)
acc_score

0.9125

Recall Score

In [ ]:
recall=recall_score(ytest,ytest_pred)
recall

0.7727272727272727

Error Rate

In [ ]:
error_rate=1-acc_score
error_rate

0.08750000000000002